name: aluguel_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  uuid: ^4.5.1
  dart_amqp: ^0.2.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
