name: aluguel_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.9.2 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
