apiVersion: apps/v1
kind: Deployment
metadata:
  name: workup-aluguel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workup-aluguel
  template:
    metadata:
      labels:
        app: workup-aluguel
    spec:
      containers:
      - name: workup-aluguel
        image: victorgasperi/workup-aluguel
        envFrom:
          - configMapRef:
              name: workup-config
          - secretRef:
              name: workup-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: workup-aluguel-service
spec:
  type: NodePort
  selector:
    app: workup-aluguel
  ports:
    - name: workup-aluguel
      protocol: TCP
      # porta que o no recebe
      port: 4002
      # porta que o no direciona dentro do pod
      targetPort: 4002
      nodePort: 32084